### ISSUE TITLE
Lua Search Error

### ISSUE THREAD

**Issue by Clawy111** [physgun-com/physgun-hud#2]
When Holding Q and  typing something into the Search Menu it breaks the menu and starts spamming your console until you in evidably crash. Only way to get rid of the error is to rejoin the server.

[physgun-hud] addons/physgun-hud/lua/strider-modules/hud/misc/cl_notifications.lua:189: attempt to index field 'Notifications' (a nil value)
  1. KillNotification - addons/physgun-hud/lua/strider-modules/hud/misc/cl_notifications.lua:189
   2. unknown - addons/physgun-hud/lua/strider-modules/hud/misc/cl_notifications.lua:47 (x20728)

![Physgun Hud](https://github.com/physgun-com/physgun-hud/assets/151641644/582c91a1-cf71-401c-8f21-ab08828bbc3f)

**Comment by Clawy111** [comment]
![image](https://github.com/physgun-com/physgun-hud/assets/151641644/637d9091-0479-4351-b265-652fe035296a)

**Comment by garryspins** [comment]
Should be fixed.
