### ISSUE TITLE
Lua Issue

### ISSUE THREAD

**Issue by CWright-91** [physgun-com/physgun-hud#3]
Unsure how to replicate just yet.  Just joined the server and it popped up

Client:
[physgun-hud-main] lua/includes/util.lua:265: attempt to perform arithmetic on local 'from' (a nil value)
  1. Lerp - lua/includes/util.lua:265
   2. unknown - addons/physgun-hud-main/lua/strider-modules/hud/elements/topbar_bits_and_knobs/cl_money.lua:22
    3. PaintManual - [C]:-1
     4. unknown - addons/physgun-hud-main/lua/strider-modules/hud/elements/cl_topbar.lua:130 (x263)

Server:
[physgun-hud-main] lua/includes/util.lua:265: attempt to perform arithmetic on local 'to' (a nil value)
1. Lerp - lua/includes/util.lua:265
2. unknown - addons/physgun-hud-main/lua/strider-modules/hud/elements/topbar_bits_and_knobs/cl_money.lua:22
3. PaintManual - [C]:-1
4. unknown - addons/physgun-hud-main/lua/strider-modules/hud/elements/cl_topbar.lua:130

**Comment by CWright-91** [comment]
Happened again upon joining

Client "*_Lil-Peach_" connected (108.227.157.138:27005).
[Fléodon's Lottery] Syncing player *_Lil-Peach_ (0 lotteries). 
Loaded 0 active (0 total) blacklisted ArcCW attachments.
[*_Lil-Peach_|5|STEAM_0:0:557629932] Lua Error:

[physgun-hud-main] lua/includes/util.lua:265: attempt to perform arithmetic on local 'to' (a nil value)
  1. Lerp - lua/includes/util.lua:265
   2. unknown - addons/physgun-hud-main/lua/strider-modules/hud/elements/topbar_bits_and_knobs/cl_money.lua:22
    3. PaintManual - [C]:-1
     4. unknown - addons/physgun-hud-main/lua/strider-modules/hud/elements/cl_topbar.lua:130


*_Lil-Peach_ has resigned!
Dropped *_Lil-Peach_ from server (Disconnect by user.)

**Comment by garryspins** [comment]
should be fixed
